AWSTemplateFormatVersion: 
Resources:
  CostAnalysisLambda:
    Type: AWS::Lambda::Function
    Properties:
         Handler: 'analyze_costs.analyze_costs'
         Code:
           S3Bucket: 'cost-optimizer-code-bucket'
           S3Key: 'lambda/cost_analysis.zip'
         Role: arn:aws:iam::148761683401:role/LambdaExecutionRole
         Runtime: 'python3.12'
         Timeout: 300
         MemorySize: 128